spring:
  application:
    name: EntityManagement

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: soc-parser-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    redis:
      host: localhost
      port: 6379

      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

    mongodb:
      uri: mongodb://root:root@localhost:27017/soc_db?authSource=admin

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password123

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: password123
  bucket-name: uploads

virustotal:
  api-key: 3c89ae4118ce7b88be512ab34608bcbe4f81d845ee00829dd6889186e13e92b3

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true   # bật /actuator/health/liveness và /actuator/health/readiness
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}