apiVersion: v1
kind: Secret
metadata:
  name: soc-secrets
  namespace: soc
type: Opaque
stringData:
  mongo-root-password: "root"
  neo4j-password:      "password123"
  minio-root-user:     "admin"
  minio-root-password: "password123"
