apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: soc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080" # Cổng mà ứng dụng của bạn trả về metrics
        prometheus.io/path: "/actuator/prometheus" #
    spec:
      containers:
        - name: backend
          image: soc/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx512m -Dspring.main.banner-mode=off -Ddebug=true"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx512m -XX:MaxRAMPercentage=75.0"
            # Mount thêm config K8s vào Spring Boot
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: file:/app/config/
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            # Ép biến môi trường để override code hard-code localhost
            - name: MINIO_ENDPOINT
              value: "http://minio:9000"
            - name: SPRING_DATA_NEO4J_URI
              value: "bolt://neo4j:7687"
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
          resources:
            requests: { memory: "256Mi", cpu: "200m" }
            limits:   { memory: "768Mi", cpu: "500m" }
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: backend-config
        - name: geoip-data
          hostPath:
            path: /data/geoip
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: soc
spec:
  selector:
    app: backend
  ports:
    - port: 8080
